name: build and upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:    
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9
          cache: true
      - run: curl -sSL https://ftp.furry.coffee/refs.tar.gz | tar xvzf -
      - run: dotnet restore --locked-mode
      - run: dotnet build SCP1162.csproj
      - uses: actions/upload-artifact@v4.5.0
        with:
          path: bin/Release
