name: build and upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:    
    runs-on: windows-latest
    steps:      
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1
      - uses: NuGet/setup-nuget@v2.0.0
      - run: nuget restore CustomItems.sln
      - run: msbuild.exe CustomItems.sln /p:platform="Any CPU" /p:configuration="Release"
      - uses: actions/upload-artifact@v4.5.0
        with:
          path: bin/Release
